require "spec"
require "webmock"
require "../src/shorturl"
require "../src/shorturl/service"
require "../src/shorturl/services/isgd"
require "../src/shorturl/services/tinyurl"
require "../src/shorturl/services/vgd"
